# Welcome to Jekyll!
#

# Site settings
title: "Noelle + A.J."
description: |
    Orlando Florida

    January 21, 2020
owner: Developer Auxilliary Systems, Ltd. # or company name
first_published: 2019 # if migrating another site, the year of your first publish
email: noelleheld@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.devaux-held.life" # the base hostname & protocol for your site

google_analytics: UA-47395716-3

social:
  #twitter: https://twitter.com/menzenski
  github: https://github.com/ajdevaux/
  #linkedin-square: https://linkedin.com/in/<username>
  #facebook-official: https://facebook.com/<username>
  #google-plus-square: https://plus.google.com/u/0/+<username>
  #email: /contact/
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
